### ISSUE TITLE
Remote I/O error when setting humidity_resolution to "0.010%" and "0.007%"

### ISSUE THREAD

**Issue by alewilh** [adafruit/Adafruit_CircuitPython_HTU31D#10]
Setting humidity_resolution to values "0.010%" and "0.007%" and querying relative_humidity results in the following error message:
```
Humidity Resolution:  0.020%
Humidity Resolution:  0.010%
Traceback (most recent call last):
  File "/home/pi/test.py", line 19, in <module>
    print(htu.relative_humidity)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_htu31d.py", line 147, in relative_humidity
    return self.measurements[1]
  File "/usr/local/lib/python3.9/dist-packages/adafruit_htu31d.py", line 163, in measurements
    i2c.write(self._buffer, end=1)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_bus_device/i2c_device.py", line 100, in write
    self.i2c.writeto(self.device_address, buf, start=start, end=end)
  File "/usr/local/lib/python3.9/dist-packages/busio.py", line 195, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 52, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_PureIO/smbus.py", line 303, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error
```

using the following code:
```python
import time
import board
import adafruit_htu31d

i2c = board.I2C()
htu = adafruit_htu31d.HTU31D(i2c)

htu.reset()
print("Humidity Resolution: ", htu.humidity_resolution)

# Setting the Relative Humidity resolution.
# Possible values are "0.020%", "0.014%", "0.010%" and "0.007%"
htu.humidity_resolution = "0.010%"
print("Humidity Resolution: ", htu.humidity_resolution)

starttime = time.time()

while True:
    print(htu.relative_humidity)
    print("")
    time.sleep(10.0 - ((time.time() - starttime) % 10.0))
```

I'm running this on Raspberry Pi OS Bullseye on a Raspberry Pi 3B+, Python3.9.2, version 1.1.11 of the library
Not sure what other information i could add here.

**Comment by jposada202020** [comment]
@alewilh Thanks for taking a look at this. Could you please try the code in pr #11. I have modified the example to verify all the settings.  there were indeed some masking problems with the settings


Tested in CP Adafruit CircuitPython 8.1.0-beta.2 on 2023-04-26; Adafruit Feather RP2040 with rp2040

**Comment by alewilh** [comment]
@jposada202020 Thank you, all resolution values now work with the new code.
